### ISSUE TITLE
Wrong pronoun

### ISSUE THREAD

**Issue by ThomasNunninger** [tailwindslabs/masteringobjectorientedphp#1]
Hey, cool that I got a copy of your book and I learned something new about you. ;-)

In your book in the chapter "About the author" there is – I assume – a wrong pronoun in two places:

> Sarah found that **he** could tackle the actual people and process problems facing businesses.

...

> Sarah started Carved Path Consulting in 2021 to consolidate and focus **his** work by consulting for businesses that want to solve their process and people problems.

**Comment by sarah-savage** [comment]
This has been fixed. Thanks for the feedback!
